### ISSUE TITLE
spelling error in RealDeviceMap_UIControlUITests.swift ?

### ISSUE THREAD

**Issue by bk227865** [RealDeviceMap/RealDeviceMap-UIControl#2]
on line 703 it reads : jsonData!["target_max_distnace"] = self.conf.targetMaxDistance

shouldn't that be : jsonData!["target_max_distance"] = self.conf.targetMaxDistance  ?

**Comment by 123FLO321** [comment]
correct 
however that's misspelled in RDM also so will not affect anything
